config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "share_on_fbs"}
  devise_scope :user do
    get '/users/auth/:provider/callback' => 'share_on_fbs#create'
  end
  devise_for :admins
  get '/print/:id' => 'homes#print', :as => :print
  get '/send_details' => 'homes#send_details', :as => :send_details
  root 'homes#index'
  resources :homes do
    collection do
      get :about_us  
      match :buy_car, via: [:get, :post]
      get :load_model
      get :load_varient
      get :sell_car
      post :save_sell_car
      get :auto_finance
      get :insurance
      match :home, via: [:get, :post]
      get :call_me
      get :faq
      get :testimonial
      get :careers
      get :contact_us
      get :associates_partners
      post :save_post_req
      get :offers
    end
    member do
      get :car_description
    end
  end
  resources :testimonials 
  resources :careers
  resources :associate_partners

  namespace :admin do
    resources :dashboards do
      collection do
        get :testimonials
        get :dealers
        get :dealer_cars
      end
      member do 
        put :approved
        match :move_to_stock, via: [:get, :put]
        put :approve_testimonial
      end
    end

    resources :stocks do
      collection do
        get :addtostock
        post :create_model
        post :create_varient
        get  :car_model
        get :display_car_varient
        get :add_master_specification
        post :create_master_specification
        get :edit_stock
        match :update_model, via: [:get, :put]
        get :list_varient
        match :update_varient, via: [:get, :put]
        get :live_cars
        get :sold_cars
        get :offer
        get :edit_offer
        put :update_offer
      end
      member do
        delete :delete_procure_enquiry
        put :sold
        put :unsold
        put :remove_offer
      end
    end

    resources :vehicles do 
      collection do 
        get :load_car_model
        get :load_varients
        get :edit_vehicle
      end
      member do 
        put :update_vehicle
      end
    end

    resources :car_specifications do
      collection do 
        get :edit_car_specification
      end
      member do 
        get :edit_car_specific
        put :update_car_specific
      end
    end

    resources :images do
      collection do
        post :create_video
      end
    end

    resources :purchase_procedures do
      collection do
        get :procure_enquiry
        get :new_evaluation
        post :create_evaluation
        get :waiting_to_evaluate
        get :deal
        put :update_deal
        get :evaluated
        get :final_deal
        put :update_final_deal
        get :purchased_car
        get :publish_vehicle
        post :save_vehicle
        get :specification_entry
        post :create_specification
      end
    end

    resources :sell_procedures do
      collection do
        get :enquiry
        get :new_evaluation
        post :create_evaluation
      end
    end

    resources :testimonials

  end

  namespace :user do
    resources :registrations do
      collection do
        get :update_status
      end
    end
  end

  namespace :dealer do
    resources :dashboards
    resources :vehicles
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_attached_file :image,
    :styles => {:thumb => "360x270#", :small=>"50x50#" },
    :default_url => "missing.jpg"
  
  validates_attachment_content_type :image, :content_type => ['image/jpeg','image/jpg', 'image/png', 'image/gif','image/bmp']  
  belongs_to :manufacturer
  belongs_to :car_model
  belongs_to :varient
  has_many :car_specification, :dependent => :destroy
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images,  :allow_destroy => true, reject_if: :all_blank
  has_many :videos, :dependent => :destroy
  belongs_to :user

  def carinfo
    "#{self.try(:varient).try(:car_model).try(:manufacturer).try(:name)}  #{self.try(:varient).try(:car_model).try(:name)}  #{self.try(:varient).try(:name)} (#{self.try(:registration_no)})"
  end
  
  scope :live_cars, lambda { where(:status => "#{Status::Vehicle::LIVE}") }
  scope :sold_cars, lambda { where(:status => "#{Status::Vehicle::SOLD}") }

  #gurgaon cars and bangalore cars which are for User && visible to User
  scope :gurgaon_cars, -> { where("location=? and visible_status=? and (car_for=? or car_for=? )", 'gurgaon', 'Visible', 'Both', 'User') }
  scope :bangalore_cars, -> { where("location=? and visible_status=? and (car_for=? or car_for=? )", 'bangalore', 'Visible', 'Both', 'User') }
  
  #these are the vehicle created by admin for user || dealer and whose status=visible
  scope :visible_user_dealer_cars, lambda { where("visible_status=? and (car_for=? or car_for=?) ", 'Visible', 'Both', 'Dealer') }
  
  validates :image, :body_style, :exterior_color, :fuel_type, :manufactured_year, :manufacturer_id, :car_model_id, :varient_id, :registration_no,
    :location, :reg_year, :milage, :sell_price, :visible_status, :engine_type, :car_for,
    :transmission, :registration_state, :seat_covers, :sterio, presence: true
  
  validates_numericality_of :milage, :only_integer => true, 
    :message => "can only be number."

  validates :sell_price , numericality: {only_float: true}

  validates :registration_no, uniqueness: true
  
  #these are the status which is created by dealer
  scope :dealer_cars, lambda { where(:status => "#{Status::Vehicle::DEALER}")}

  scope :bangalore_offers, -> { where("location=? and (offer_price IS NOT NULL and offer_price != '')", 'bangalore') }
  scope :gurgaon_offers, -> { where("location=? and (offer_price IS NOT NULL and offer_price != '')", 'gurgaon') }

  
  def post(post)
    me = FbGraph::User.me(ShareFb.first.secret_token)
    me.feed!(
      :message => "Car Enquiry",
      :name => post.carinfo,
      :link => BASE_URL,
      :description => "Color: #{post.exterior_color} Location: #{post.location} Body Style: #{post.body_style} Mileage: #{post.milage} Fuel Type: #{post.fuel_type} Reg Yr: #{post.reg_year} Price: #{post.sell_price}"
    )
  end
end

app/controllers/admin/vehicles_controller.rb
class Admin::VehiclesController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def new
    @vehicle = Vehicle.new
    @manufacturers = Manufacturer.all
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
  end

  def create
    @manufacturers = Manufacturer.all
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
    @vehicle = Vehicle.new(vehicle_params)
    p "---------------------------------"
    @vehicle.manufacturer_id = params[:manufacturer_id]
    if params[:varient].present?
      @vehicle.varient_id = params[:varient][:varient_id] 
      @vehicle.car_model_id = params[:varient][:car_model_id]
    end
    p "---------------------------------"

    @vehicle.status = "#{Status::Vehicle::LIVE}"
    if @vehicle.save
      flash[:notice] = "Car record is saved successfully."
      redirect_to new_admin_vehicle_path
    else
      render :action => :new
    end
  end
  
  def edit_vehicle
    @vehicles = Vehicle.all
  end
  
  def edit
    @manufacturers = Manufacturer.all
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
    @vehicle = Vehicle.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def update_vehicle
    @vehicle = Vehicle.find(params[:id])
    p "--------------------------------------"
    p @vehicle
    if @vehicle.update_attributes(vehicle_params)
      flash[:notice] = "Car record is updated successfully."
    end
    respond_to do |format|
      format.js
    end
  end

  def load_car_model
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
  end

  def load_varients
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
  end
  
  def destroy
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.destroy
      flash[:notice] = "Car record is deleted successfully."
      respond_to do |format|
        format.js
      end
    end
  end

  private
  def vehicle_params
    params.require(:vehicle).permit!
  end
end

app/controllers/dealer/dashboards_controller.rb
class Dealer::DashboardsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @vehicles = Vehicle.visible_user_dealer_cars.all.page(params[:page]).per(15)
  end
end

app/controllers/dealer/vehicles_controller.rb
class Dealer::VehiclesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @vehicle = Vehicle.new
    @manufacturers = Manufacturer.all
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
  end

  def create
    @manufacturers = Manufacturer.all
    @car_models = CarModel.where("manufacturer_id=?", params[:manufacturer_id])
    @varients = Varient.where("car_model_id=?", params[:car_model_id])
    @vehicle = Vehicle.new(vehicle_params.merge(:varient_id => params[:varient][:varient_id], :car_model_id => params[:varient][:car_model_id], :manufacturer_id => params[:manufacturer_id], :user_id => current_user.id, :visible_status => "Visible", :car_for => "Dealer"))
    @vehicle.status = "#{Status::Vehicle::DEALER}"
    if @vehicle.save
      redirect_to dealer_vehicles_path
    else
      render :action => :new
    end 
  end

  def index
    @vehicles = current_user.vehicles.all.page(params[:page]).per(15)
  end
  
  private
  def vehicle_params
    params.require(:vehicle).permit!
  end
end

app/helpers/admin/vehicles_helper.rb
module Admin::VehiclesHelper
end

app/helpers/dealer/dashboards_helper.rb
module Dealer::DashboardsHelper
end

app/helpers/dealer/vehicles_helper.rb
module Dealer::VehiclesHelper
end

app/views/dealer/vehicles/_dealer_vehicles.html.erb
<div class="table-responsive">
  <table class="table table-stripped table-hover">
    <tr>
      <th>Car ID</th>
      <th>Car_Detail</th>
      <th>Kms & Exp.Price</th>
      <th>Reg. Details</th>
      <th>Status</th>
      <th></th>
    </tr>

    <%@vehicles.each do |s|%>
      <tr>
        <td>
          <%= s.id %>
        </td>
      
        <td>
          <b>Car:</b> <%= s.try(:carinfo) %> <br/>
          <b>Make Yr: </b> <%= s.try(:manufactured_year) %> <br/>
          <b>Color: </b> <%= s.try(:exterior_color).capitalize %>
        </td>

        <td>
          <b>KMs.Done:</b> <%= s.try(:milage) %>  <br/>
          <b>Exptd. Price:</b> <%= s.try(:sell_price) %>
        </td>

        <td>
          <b>City:</b> <%= s.try(:location).capitalize %>  <br/>
          <b>Reg.No:</b> <%= s.try(:registration_no) %>  <br/>
          <b>Reg. at:</b> <%= s.try(:registration_state).capitalize %>
        </td>

        <td>
          <%= s.try(:status) == "#{Status::Vehicle::LIVE}" ? ("In Admin Stock") : (s.try(:status) == "#{Status::Vehicle::SOLD}" ? ("Sold Out") : ("In your Stock") ) %>
        </td>        
      </tr>
    <% end %>
  </table>
  
  <%= paginate @vehicles %>

app/views/dealer/vehicles/index.html.erb
<div class="form-group">
  <div class="row">
    <div class="col-sm-12">
     <div class="form-group">
        <%= link_to "Add New Vehicle", new_dealer_vehicle_path, :class => "btn btn-md btn-warning" %>
     </div>
      <%= render :partial => "dealer_vehicles" %>
    </div>
  </div>
</div>

app/views/dealer/vehicles/new.html.erb
<div class="panel-body">
  <%= form_for @vehicle, :url => "/dealer/vehicles", :method => "POST" do |f| %>

    <% if @vehicle.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% @vehicle.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <b>Car Detail Form</b>
        </div>
      </div>
    </div>
    <hr/>

    <div class="row">
      <div class="col-sm-6">

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Manufacturer</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= select_tag :manufacturer_id, options_for_select([["- Select -", ""]] + @manufacturers.map {|m| [m.name, m.id]}), :class => "form-control", :id => "manufacturer_id", :onchange => "load_carmodels(this.value)" %>
            </div>
          </div>
        </div>

        <div id="load_carmodels">
          <%= render :partial => "admin/vehicles/load_carmodels" %>
        </div>

        <div id="load_varients">
          <%= render :partial => "admin/vehicles/load_varients" %>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Car Image</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.file_field :image %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Location</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :location, options_for_select([["Select", ""],["Bangalore","bangalore"],["Delhi","gurgaon"]], :selected => f.object.location), {}, :class => "form-control", :rows => "1" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Body style</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :body_style, options_for_select([["-- Select body type", ""], ["Hatchback", "Hatchback"], ["Convertible", "Convertible"], ["MUV_VAN", "MUV_VAN"],["Sedan", "Sedan"], ["SUV", "SUV"]]), {}, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Exterior Color</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :exterior_color, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Reg. Year</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :reg_year, :class => "form-control" %>
            </div>
          </div>
        </div>


        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Manufactured Year</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :manufactured_year, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>KMs Done</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :milage, :class => "form-control" %>
            </div>
          </div>
        </div>

      </div>

      <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-3">
              <div class="form-group">
                <b>Fuel type</b>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group">
                <%= f.select :fuel_type, options_for_select([["Select",""],["Petrol","Petrol"],["Diesel","Diesel"],["CNG","CNG"],["LPG","LPG"],["Hybrid","Hybrid"]],:selected => f.object.fuel_type), {}, :class => "form-control" %>
              </div>
            </div>
          </div>
        
        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Engine Type</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :engine_type, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Transmission</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :transmission, options_for_select([["Select", ""], ["Manual", "Manual"], ["Automatic", "Automatic"]]), {}, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Registration State</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :registration_state, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Registration No.</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :registration_no, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Sell Price</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.text_field :sell_price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Music System</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :sterio, options_for_select([["-Select-", ""],["Yes","Yes"],["No","No"]], :selected => f.object.sterio),{}, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <b>Seat Covers</b>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= f.select :seat_covers,  options_for_select([["-Select-", ""],["Fabric","Fabric"],["Leather","Leather"],["Faux leather","Faux leather"]],:selected => f.object.seat_covers),{}, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3">
            <div class="form-group">
              <%= f.submit "Save", :class => "btn btn-md btn-warning", :id => "save_vehicle" %>
            </div>
          </div>
        </div>

      </div>
    <% end %> 
  </div>

  <script>
    $(document).on("click", "#save_vehicle", function() {
      var make_id = $("#manufacturer_id").val();
      if (make_id === '') {
        alert("Please Select Manufacturer to Proceed.");
        return false;
      }
    });
    
    function load_carmodels(obj) {
      $.ajax({
        url: "/admin/vehicles/load_car_model",
        type: "GET",
        dataType: "Script",
        data: {
          manufacturer_id: obj
        }
      });
    }

    function load_varients(car_model_id) {
      $.ajax({
        url: "/admin/vehicles/load_varients",
        dataType: "Script",
        type: "GET",
        data: {
          car_model_id: car_model_id
        }
      });
    }
  </script>