config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "share_on_fbs"}
  devise_scope :user do
    get '/users/auth/:provider/callback' => 'share_on_fbs#create'
  end
  devise_for :admins
  get '/print/:id' => 'homes#print', :as => :print
  get '/send_details' => 'homes#send_details', :as => :send_details
  root 'homes#index'
  resources :homes do
    collection do
      get :about_us  
      match :buy_car, via: [:get, :post]
      get :load_model
      get :load_varient
      get :sell_car
      post :save_sell_car
      get :auto_finance
      get :insurance
      match :home, via: [:get, :post]
      get :call_me
      get :faq
      get :testimonial
      get :careers
      get :contact_us
      get :associates_partners
      post :save_post_req
      get :offers
    end
    member do
      get :car_description
    end
  end
  resources :testimonials 
  resources :careers
  resources :associate_partners

  namespace :admin do
    resources :dashboards do
      collection do
        get :testimonials
        get :dealers
        get :dealer_cars
      end
      member do 
        put :approved
        match :move_to_stock, via: [:get, :put]
        put :approve_testimonial
      end
    end

    resources :stocks do
      collection do
        get :addtostock
        post :create_model
        post :create_varient
        get  :car_model
        get :display_car_varient
        get :add_master_specification
        post :create_master_specification
        get :edit_stock
        match :update_model, via: [:get, :put]
        get :list_varient
        match :update_varient, via: [:get, :put]
        get :live_cars
        get :sold_cars
        get :offer
        get :edit_offer
        put :update_offer
      end
      member do
        delete :delete_procure_enquiry
        put :sold
        put :unsold
        put :remove_offer
      end
    end

    resources :vehicles do 
      collection do 
        get :load_car_model
        get :load_varients
        get :edit_vehicle
      end
      member do 
        put :update_vehicle
      end
    end

    resources :car_specifications do
      collection do 
        get :edit_car_specification
      end
      member do 
        get :edit_car_specific
        put :update_car_specific
      end
    end

    resources :images do
      collection do
        post :create_video
      end
    end

    resources :purchase_procedures do
      collection do
        get :procure_enquiry
        get :new_evaluation
        post :create_evaluation
        get :waiting_to_evaluate
        get :deal
        put :update_deal
        get :evaluated
        get :final_deal
        put :update_final_deal
        get :purchased_car
        get :publish_vehicle
        post :save_vehicle
        get :specification_entry
        post :create_specification
      end
    end

    resources :sell_procedures do
      collection do
        get :enquiry
        get :new_evaluation
        post :create_evaluation
      end
    end

    resources :testimonials

  end

  namespace :user do
    resources :registrations do
      collection do
        get :update_status
      end
    end
  end

  namespace :dealer do
    resources :dashboards
    resources :vehicles
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :vehicle
  has_attached_file :image,
    :styles => {:thumb => "360x270#", :small=>"50x50#" }
  validates_attachment_content_type :image, :content_type => ['image/jpeg','image/jpg', 'image/png', 'image/gif','image/bmp']
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  before_filter :authenticate_admin!
  def new
    @vehicle = Vehicle.new
    
    if @vehicle.images.blank?
      @vehicle.images.build
    end

    @video = Video.new
    @vehicles = Vehicle.all
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
   
    @vehicles = Vehicle.all
    if @vehicle.update_attributes(vehicle_params)
      redirect_to new_admin_image_path
    else
      render :action => :new
    end
  end

  def create_video
    @vehicles = Vehicle.all
    @video = Video.new(video_params)
    if @video.save
      redirect_to new_admin_image_path
    else
      render :action => :new
    end
  end

  private
  def image_params
    params.require(:image).permit!
  end 

  def video_params
    params.require(:video).permit!
  end

  def vehicle_params
    params.require(:vehicle).permit(:id, images_attributes: [:id, :vehicle_id, :image, :_destroy])
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/new.html.erb
<%= render :partial => "admin/shared/stocks_navbar" %>

<div class="panel-body">
  <div class="row">
    <div class="col-sm-6">
      <%= nested_form_for @vehicle, :url => "/admin/images", :method => "POST", :html => {:multipart => true} do |f| %>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <b>Add Images of Cars</b>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">
              <b>Vehicle</b>
            </div>

            <div class="col-sm-6">
              <%= select_tag :vehicle_id, options_for_select([["- Select -", ""]] + @vehicles.all.map {|x| [x.carinfo, x.id]}), :class => "form-control", :id => "select_vehicle1" %>
            </div>
          </div>
        </div>

        <%= f.fields_for :images do |task_form| %>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-6">
                <%= task_form.file_field :image %>
              </div>

              <div class="col-sm-6">
                <%= task_form.link_to_remove '<i class="glyphicon glyphicon-remove"></i>'.html_safe %>
              </div>
            </div>
          </div>
        <% end %>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.link_to_add "<i class='glyphicon glyphicon-plus'></i> Add More Image".html_safe, :images %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.submit "Create Image", :class => "btn btn-md btn-warning", :id => "submit1" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-sm-6">
      <%= form_for @video, :url => create_video_admin_images_path, :method => "POST" do |f| %>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <b>Add Videos of Cars</b>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">
              <%= f.label :vehicle_id, "Vehicle" %>
            </div>

            <div class="col-sm-6">
              <%= f.select :vehicle_id, options_for_select([["- Select -", ""]] + @vehicles.all.map {|x| [x.carinfo, x.id]}), {}, :class => "form-control",:id => "select_vehicle2" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">
              <%= f.label :video_url, "Video Url" %>
            </div>

            <div class="col-sm-6">
              <%= f.text_field :video_url, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <b class="text-muted"> Ex. http://www.youtube.com/embed/X3HlFewKByw</b>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
              <%= f.submit :class => "btn btn-md btn-warning", :id => "submit2" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).on("click", "#submit1", function() {
    var vehicle = $("#select_vehicle1").val();
    if (vehicle == '') {
      alert("Please select vehicle first")
      return false;
    }
  });

  $(document).on("click", "#submit2", function() {
    var vehicle = $("#select_vehicle2").val();
    if (vehicle == '') {
      alert("Please select vehicle first")
      return false;
    }
  });
</script>