config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "share_on_fbs"}
  devise_scope :user do
    get '/users/auth/:provider/callback' => 'share_on_fbs#create'
  end
  devise_for :admins
  get '/print/:id' => 'homes#print', :as => :print
  get '/send_details' => 'homes#send_details', :as => :send_details
  root 'homes#index'
  resources :homes do
    collection do
      get :about_us  
      match :buy_car, via: [:get, :post]
      get :load_model
      get :load_varient
      get :sell_car
      post :save_sell_car
      get :auto_finance
      get :insurance
      match :home, via: [:get, :post]
      get :call_me
      get :faq
      get :testimonial
      get :careers
      get :contact_us
      get :associates_partners
      post :save_post_req
      get :offers
    end
    member do
      get :car_description
    end
  end
  resources :testimonials 
  resources :careers
  resources :associate_partners

  namespace :admin do
    resources :dashboards do
      collection do
        get :testimonials
        get :dealers
        get :dealer_cars
      end
      member do 
        put :approved
        match :move_to_stock, via: [:get, :put]
        put :approve_testimonial
      end
    end

    resources :stocks do
      collection do
        get :addtostock
        post :create_model
        post :create_varient
        get  :car_model
        get :display_car_varient
        get :add_master_specification
        post :create_master_specification
        get :edit_stock
        match :update_model, via: [:get, :put]
        get :list_varient
        match :update_varient, via: [:get, :put]
        get :live_cars
        get :sold_cars
        get :offer
        get :edit_offer
        put :update_offer
      end
      member do
        delete :delete_procure_enquiry
        put :sold
        put :unsold
        put :remove_offer
      end
    end

    resources :vehicles do 
      collection do 
        get :load_car_model
        get :load_varients
        get :edit_vehicle
      end
      member do 
        put :update_vehicle
      end
    end

    resources :car_specifications do
      collection do 
        get :edit_car_specification
      end
      member do 
        get :edit_car_specific
        put :update_car_specific
      end
    end

    resources :images do
      collection do
        post :create_video
      end
    end

    resources :purchase_procedures do
      collection do
        get :procure_enquiry
        get :new_evaluation
        post :create_evaluation
        get :waiting_to_evaluate
        get :deal
        put :update_deal
        get :evaluated
        get :final_deal
        put :update_final_deal
        get :purchased_car
        get :publish_vehicle
        post :save_vehicle
        get :specification_entry
        post :create_specification
      end
    end

    resources :sell_procedures do
      collection do
        get :enquiry
        get :new_evaluation
        post :create_evaluation
      end
    end

    resources :testimonials

  end

  namespace :user do
    resources :registrations do
      collection do
        get :update_status
      end
    end
  end

  namespace :dealer do
    resources :dashboards
    resources :vehicles
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_filter :authenticate_admin!
  def index
  end
  
  def testimonials
    @testimonials = Testimonial.all.page(params[:page]).per(15)
  end

  def approve_testimonial
    @testimonial = Testimonial.find(params[:id])
    @testimonial.approve? ? (@testimonial.update_attributes(approve: false)) : (@testimonial.update_attributes(approve: true))
    respond_to do |format|
      format.js {
        @testimonial
      }
    end
  end
  
  def dealers
    @associate_partners = AssociatePartner.all.page(params[:page]).per(15)
    @user = User.new
  end
  
  def approved
    @associate_partner = AssociatePartner.find(params[:id])
    @user = User.where("email = '#{@associate_partner.email}'").first
    @associate_partner.status == "Yes" ? @associate_partner.update_attributes(:status => "No") : @associate_partner.update_attributes(:status => "Yes")
    @user.approved == true ? (@user.update_attribute(:approved, false)) : (@user.update_attribute(:approved, true))
  end
  
  def dealer_cars
    @vehicles = Vehicle.dealer_cars.all.page(params[:page]).per(15)
  end
  
  def move_to_stock
    @vehicle = Vehicle.find(params[:id])
    @vehicle.status = "#{Status::Vehicle::LIVE}"
    if @vehicle.save(:validate => false)
      flash[:notice] = "You have successfully added this vehicle to your stock."
      redirect_to dealer_cars_admin_dashboards_path
    end
  end
end

app/controllers/dealer/dashboards_controller.rb
class Dealer::DashboardsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @vehicles = Vehicle.visible_user_dealer_cars.all.page(params[:page]).per(15)
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/dealer/dashboards_helper.rb
module Dealer::DashboardsHelper
end

app/views/admin/dashboards/_dealer_vehicles.html.erb
<div class="table-responsive">
  <table class="table table-stripped table-hover">
    <tr>
      <th>Car ID</th>
      <th>Car_Detail</th>
      <th>Kms & Exp.Price</th>
      <th>Reg. Details</th>
      <th>Dealer Information</th>
      <th>Action</th>
    </tr>

    <%@vehicles.each do |s|%>
      <tr>
        <td>
          <%= s.id %>
        </td>
        <td>
          <b>Car:</b> <%= s.try(:carinfo) %> <br/>
          <b>Make Yr: </b> <%= s.try(:manufactured_year) %> <br/>
          <b>Color: </b> <%= s.try(:exterior_color).capitalize%>
        </td>

        <td>
          <b>Km.Done:</b> <%= s.try(:milage) %>  <br/>
          <b>Exptd. Price:</b> <%= number_to_currency(s.try(:sell_price), :unit => "Rs.") %>
        </td>

        <td>
          <b>City:</b> <%= s.try(:location).capitalize %>  <br/>
          <b>Reg. No:</b> <%= s.try(:registration_no) %>  <br/>
          <b>Reg. at:</b> <%= s.try(:registration_state).capitalize %>
        </td>

        <td>
          <% @partner = AssociatePartner.user_partner(s.try(:user).try(:email)) %>
          <b>Email:</b> <%= @partner.email %> <br/>
          <b>Name:</b> <%= @partner.name.titleize %> <br/>
          <b>Phone:</b> <%= @partner.phone %> <br/>
          <b>Address:</b> <%= @partner.address.capitalize %> <br/>
          <b>Type:</b> <%= @partner.dealer_type.capitalize %> <br/>
          <b>Dealer Name:</b> <%= @partner.dealer_name.capitalize %>
        </td>

        <td>
          <%= link_to "Move To Stock", move_to_stock_admin_dashboard_path(s.id), :method => "PUT", :class => "btn btn-sm btn-warning"  %>
        </td>
      </tr>
    <% end %>
  </table>
  
    <%= paginate @vehicles %>

app/views/admin/dashboards/_form.html.erb
<%= form_for @user, url: "/users", method: "POST" do |f| %>
  <%= f.email_field :email %>
<br/>
  <%= f.password_field :password %>
<br/>
<%= f.password_field :password_confirmation, autocomplete: "off" %>
<br/>
  <%= f.submit %>
<% end %>

app/views/admin/dashboards/approve_testimonial.js.erb
alert("You have <%= @testimonial.approve? ? 'Approved' : 'Disapprove' %> this testimonial");
window.location.reload();

app/views/admin/dashboards/approved.js.erb
window.location.reload();

app/views/admin/dashboards/dealer_cars.html.erb
<%= render :partial=>"/admin/shared/dealers_navbar" %>

<div class="form-group">
  <div class="row">
    <div class="col-sm-12">
      <%= render :partial => "dealer_vehicles" %>
    </div>
  </div>
</div>

app/views/admin/dashboards/dealers.html.erb
<%= render :partial=>"/admin/shared/dealers_navbar" %>
<tr><td>Dealer's Detail </td></tr> 
<div class="table-responsive">
    <table class="table table-stripped table-hover">
        <tr>
            <th>DealerID</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Email_ID</th>
            <th>Address</th>
            <th>Type</th>
            <th>Approved</th>
            <th>PostDate</th>
            <th></th>
        </tr>
        <% @associate_partners.each do |associate_partner| %>
          <tr>
              <td><%= associate_partner.id  %> </td>
              <td><%= associate_partner.name.titleize %> </td>
              <td><%= associate_partner.phone %> </td>
              <td><%= associate_partner.email %> </td>
              <td><%= associate_partner.address.capitalize %> </td>
              <td><%= associate_partner.dealer_type %> </td>
              <td><%= associate_partner.status  %> </td>
              <td><%= associate_partner.created_at.strftime("%d-%m-%Y")%> </td>
              <% @user1 = User.find_by_email(associate_partner.email) %>
              <td>
                  <% if !@user1.present? %>
                    <a class="btn btn-primary announce" data-toggle="modal" data-id="<%= associate_partner.email %>" >Register</a>
                  <% else %>
                    <%= link_to associate_partner.status == "Yes" ? "Disapprove" : "Approve", approved_admin_dashboard_path(associate_partner.id), :method => "PUT", :remote => true, :class => "btn btn-warning btn-sm" %>
                  <% end %>
              </td>
          </tr>
        <%end%>
    </table> 
</div>

<div class="modal fade bs-example-modal-sm" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <%= render :partial => "user/registrations/new" %>
    </div>
</div>

<script>
  $(document).ready(function () {
      $(".announce").click(function () { // Click to only happen on announce links
          $("#user_email").val($(this).data('id'));
          $('#myModal1').modal('show');
      });
  });
</script>
    <%= paginate @associate_partners %>

app/views/admin/dashboards/index.html.erb
<%= render :partial => "admin/shared/dashboards_navbar" %>

<div class="row">
  <div class="col-sm-4">
    <%= link_to image_tag("imgs/stock-manage.png", :height => "200px", :width => "220px"), addtostock_admin_stocks_path %>
  </div>

  <div class="col-sm-4">
    <%= link_to image_tag("imgs/testimonials.jpg", :height => "200px", :width => "230px"), testimonials_admin_dashboards_path %>
  </div>

  <div class="col-sm-4">
    <%= link_to image_tag("imgs/dealer.png", :height => "200px", :width => "200px"), dealers_admin_dashboards_path %>
  </div>
</div>

app/views/admin/dashboards/testimonials.html.erb
<%= render :partial => "admin/shared/testimonials_navbar" %>

<div class="pull-right" style="margin-bottom: 5px;"><%= link_to "Add New Testimonial", new_admin_testimonial_path, :class => "btn btn-md btn-warning" %></div>
<table class="table table-stripped table-hover">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email_ID</th>
    <th>Testimonial</th>
    <th>PostDate</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  <%@testimonials.each do |testimonial|%>
    <tr>
      <td><%= testimonial.id %></td>
      <td><%= testimonial.name.capitalize %></td>
      <td><%= testimonial.email %></td>
      <td>
      <% if testimonial.display == "User_create" %>
        <%= testimonial.testimonial %>
      <% elsif testimonial.display == "Admin_create" %>    
        <%= image_tag testimonial.customer_image(:small) %> 
        <%= image_tag testimonial.feedback_image(:small) %> 
      <% end %>
      </td>
      <td><%= testimonial.created_at.strftime("%d-%m-%Y") %></td>
      <td><%= testimonial.is_approved?.capitalize %></td>
      <td><%= link_to "#{testimonial.approve? ? 'Disapprove' : 'Approve'}", approve_testimonial_admin_dashboard_path(testimonial.id), :method => "PUT", :remote => true %></td>
    </tr>
  <%end%>
</table>
<%= paginate @testimonials %>