config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "share_on_fbs"}
  devise_scope :user do
    get '/users/auth/:provider/callback' => 'share_on_fbs#create'
  end
  devise_for :admins
  get '/print/:id' => 'homes#print', :as => :print
  get '/send_details' => 'homes#send_details', :as => :send_details
  root 'homes#index'
  resources :homes do
    collection do
      get :about_us  
      match :buy_car, via: [:get, :post]
      get :load_model
      get :load_varient
      get :sell_car
      post :save_sell_car
      get :auto_finance
      get :insurance
      match :home, via: [:get, :post]
      get :call_me
      get :faq
      get :testimonial
      get :careers
      get :contact_us
      get :associates_partners
      post :save_post_req
      get :offers
    end
    member do
      get :car_description
    end
  end
  resources :testimonials 
  resources :careers
  resources :associate_partners

  namespace :admin do
    resources :dashboards do
      collection do
        get :testimonials
        get :dealers
        get :dealer_cars
      end
      member do 
        put :approved
        match :move_to_stock, via: [:get, :put]
        put :approve_testimonial
      end
    end

    resources :stocks do
      collection do
        get :addtostock
        post :create_model
        post :create_varient
        get  :car_model
        get :display_car_varient
        get :add_master_specification
        post :create_master_specification
        get :edit_stock
        match :update_model, via: [:get, :put]
        get :list_varient
        match :update_varient, via: [:get, :put]
        get :live_cars
        get :sold_cars
        get :offer
        get :edit_offer
        put :update_offer
      end
      member do
        delete :delete_procure_enquiry
        put :sold
        put :unsold
        put :remove_offer
      end
    end

    resources :vehicles do 
      collection do 
        get :load_car_model
        get :load_varients
        get :edit_vehicle
      end
      member do 
        put :update_vehicle
      end
    end

    resources :car_specifications do
      collection do 
        get :edit_car_specification
      end
      member do 
        get :edit_car_specific
        put :update_car_specific
      end
    end

    resources :images do
      collection do
        post :create_video
      end
    end

    resources :purchase_procedures do
      collection do
        get :procure_enquiry
        get :new_evaluation
        post :create_evaluation
        get :waiting_to_evaluate
        get :deal
        put :update_deal
        get :evaluated
        get :final_deal
        put :update_final_deal
        get :purchased_car
        get :publish_vehicle
        post :save_vehicle
        get :specification_entry
        post :create_specification
      end
    end

    resources :sell_procedures do
      collection do
        get :enquiry
        get :new_evaluation
        post :create_evaluation
      end
    end

    resources :testimonials

  end

  namespace :user do
    resources :registrations do
      collection do
        get :update_status
      end
    end
  end

  namespace :dealer do
    resources :dashboards
    resources :vehicles
  end
end

app/views/admin/shared/_dashboards_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav">
        <li>
          <%=link_to("Log Out", destroy_admin_session_path, :method => :delete, :class => "btn btn-sm")%>
       </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/shared/_dealers_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", admin_dashboards_path %></li> 
        <li><%= link_to "Dealer", dealers_admin_dashboards_path %></li>
        <li><%= link_to "Dealer's Car", dealer_cars_admin_dashboards_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/shared/_stocks_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", admin_dashboards_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Stock Management <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Add Model & Varient", addtostock_admin_stocks_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Add Master Specification", add_master_specification_admin_stocks_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Add Car Details", new_admin_vehicle_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Add Car Specification",  new_admin_car_specification_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Add Car Images & Video", new_admin_image_path %></li>
            <li class="divider"></li>
            <li><%= link_to "View Live Cars", live_cars_admin_stocks_path %></li>
            <li class="divider"></li>
            <li><%= link_to "View Sold Cars", sold_cars_admin_stocks_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Update Stock <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Model & Varient", edit_stock_admin_stocks_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Car Details", edit_vehicle_admin_vehicles_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Car Specification", edit_car_specification_admin_car_specifications_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Offer <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Add / Remove", offer_admin_stocks_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Procure Dept. <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Enquiry", procure_enquiry_admin_purchase_procedures_path %> </li>
            <li class="divider"></li>
            <li><%= link_to "Waiting for Evaluation", waiting_to_evaluate_admin_purchase_procedures_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Evaluated", evaluated_admin_purchase_procedures_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Accept in Stock", purchased_car_admin_purchase_procedures_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sell <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Car Specific Enquiry", enquiry_admin_sell_procedures_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li> <%=link_to("Log Out", destroy_admin_session_path, :method => :delete)%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/shared/_testimonials_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", admin_dashboards_path %></li>
        <li><%= link_to "Testimonials", testimonials_admin_dashboards_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>